config/routes.rb
SocialThing::Application.routes.draw do
  resources :users
  resource :session
  resource :password_reset, :only  => [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password
  before_validation :ensure_session_token
  validates :email, :password_digest, :session_token, :presence => true
  validates :password, :length => { :minimum => 5 }, :on => :create

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def password=(plaintext)
    @password = plaintext
    self.password_digest = BCrypt::Password.create(plaintext)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  include ApplicationHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
    render :new
  end

  def create
    @reset_token = SecureRandom::urlsafe_base64(16)
    @user = User.find_by_email(params[:user][:email])
    @user.reset_token = @reset_token
    @user.save!
    msg = PasswordResetMailer.reset_email(@user, @reset_token).deliver!
    redirect_to new_session_url
  end

  def edit
    @user = User.find_by_reset_token(params[:reset_token])
    p @user
    render :edit
  end

  def update
    @user = User.find(params[:user][:id])
    p @user
    @user.password=(params[:user][:password])
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user.is_password?(params[:user][:password])
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid name or password"]
      render :new
    end
  end

  def destroy
    @user = current_user
    logout_user!(@user)
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  def edit
  end

  def update
  end

  def index
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  def create_password_reset_url(reset_token)
    url = Addressable::URI.new(
      :scheme => 'http',
      :host => 'localhost:3000',
      :path => "#{edit_password_reset_path}",
      :query_values => { :reset_token => "#{reset_token}" }
    ).to_s
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  # def authenticate
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "shared/errors"%>
  <% if logged_in? %>
    <%= button_to("Log out", session_url, :method => :delete) %>
  <% else %>
    <%= link_to("Sign in", new_session_url) %>
    <%= link_to("Sign up", new_user_url) %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<p><%= @user.email %></p>
<form action="<%= password_reset_url %>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="user[id]" value="<%= @user.id %>">
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <input type="submit" value"Set new password">
</form>

app/views/password_resets/new.html.erb
<h2>Reset your password</h2>
<form action="<%= password_reset_url %>" method="POST">
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">
  <input type="submit" value="Send password reset email">
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] && flash[:errors].each do |error|%>
  <%= error%>
  <br>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<form action="<%= users_url %>" method="POST">
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<h3><%=@user.email%></h3>